### ISSUE TITLE
This package is not signed

### ISSUE THREAD

**Issue by JohnHogan86** [aws/aws-secretsmanager-caching-net#146] opened 2024-07-25 19:32 UTC
Could not load file or assembly 'Amazon.SecretsManager.Extensions.Caching, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required.

**Comment by simonmarty** [comment] 2024-11-11 20:02
Closing as duplicate of #29

**Closed by simonmarty** 2024-11-11 20:02 UTC
