### ISSUE TITLE
Caching doesn't work

### ISSUE THREAD

**Issue by srikanth-kusumba** [aws/aws-secretsmanager-caching-net#78] opened 2023-02-23 19:14 UTC
Bug: 
The GetSecretString is returning the secret but caching doesn't seem to be working

**To Reproduce**
CloudTrail event history shows every event (if the TTL is set to default 1hr, each hit to the getsecretstring is recorded in event history.

**Expected behavior**
AWS Secret Manager Service should not be hit when the secret is fetched within cache config TTL

**Environment**
.Net 7

**Comment by jbct** [comment] 2023-04-18 20:18
Thank you Srikanth. Can you post a bit more about the code snippets you're using and how you're instantiating the client?

**Comment by simonmarty** [comment] 2023-04-27 18:26
I tried reproducing your issue with the following snippet
```csharp
using Amazon.SecretsManager.Extensions.Caching;

internal class Program
{
    private static async Task Main(string[] args)
    {
        var cache = new SecretsManagerCache();

        String? secret = null;

        for (int i = 0; i < 10; i++)
        {
            secret = await cache.GetSecretString("somesecretid");
        }
        if (secret != null)
        {
            Console.WriteLine(secret);
        }
    }
}
```

I'm only seeing 3 CloudTrail events for the above call
- A `DescribeSecret` on the secret
- A `GetSecretValue` on that same secret
- A KMS `Decrypt` call to decrypt the secret

**Comment by simonmarty** [comment] 2023-04-27 18:27
Closing as this is likely caused by some error on your side. Please reopen if you identify a bug in our caching library.

**Closed by simonmarty** 2023-04-27 18:27 UTC
Labels: bug
